version: '3'

services:

  producer:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      EMAILS_TOPIC: emails.topic
      EMAILS_BATCH_SIZE: 10
      SPAM_URL: "http://untroubled.org/spam/1998.7z"

networks:
  default:
    external:
      name: kafka-network
